# REQUIRED LIBRARIES

In [31]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Nishith\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Nishith\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# 1.Data Gathering 

In [32]:
df = pd.read_csv(r"C:\Users\Nishith\Downloads\train (1).csv")
df.head()


id                                              title              author   
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus  \
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

# 2. Data Analysis

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [34]:
df['label'].value_counts()

label
1    10413
0    10387
Name: count, dtype: int64

In [35]:
df.shape

(20800, 5)

In [25]:
df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [36]:
df = df.dropna() #Handled Missing values by droping those rows

In [37]:
df.isna().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [38]:
df.shape

(18285, 5)

In [39]:
df.reset_index(inplace=True)
df.head()

index  id                                              title   
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...  \
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text   
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  \
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

In [40]:
df['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [41]:
df = df.drop(['id','text','author'],axis = 1)
df.head()

index                                              title  label
0      0  House Dem Aide: We Didn’t Even See Comey’s Let...      1
1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...      0
2      2                  Why the Truth Might Get You Fired      1
3      3  15 Civilians Killed In Single US Airstrike Hav...      1
4      4  Iranian woman jailed for fictional unpublished...      1

# 3.Data Preprocessing 

## 1.Tokenization

In [42]:
sample_data = 'The quick brown fox jumps over the lazy dog'
sample_data = sample_data.split()
sample_data

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

## 2. Make Lowercase

In [43]:
sample_data = [data.lower() for data in sample_data]
sample_data

['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

## 3. Remove Stopwords

In [44]:
stopwords = stopwords.words('english')
print(stopwords[0:10])
print(len(stopwords))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]
179


In [45]:
sample_data = [data for data in sample_data if data not in stopwords]
print(sample_data)
len(sample_data)

['quick', 'brown', 'fox', 'jumps', 'lazy', 'dog']


6

## 4. Stemming

In [46]:
ps = PorterStemmer()
sample_data_stemming = [ps.stem(data) for data in sample_data]
print(sample_data_stemming)

['quick', 'brown', 'fox', 'jump', 'lazi', 'dog']


## 5. Lemmatization

In [47]:
lm = WordNetLemmatizer()
sample_data_lemma = [lm.lemmatize(data) for data in sample_data]
print(sample_data_lemma)

['quick', 'brown', 'fox', 'jump', 'lazy', 'dog']


In [48]:
lm = WordNetLemmatizer()
corpus = []
for i in range (len(df)):
    review = re.sub('[^a-zA-Z0-9]', ' ', df['title'][i])
    review = review.lower()
    review = review.split()
    review = [lm.lemmatize(x) for x in review if x not in stopwords]
    review = " ".join(review)
    corpus.append(review)

In [49]:
len(corpus)

18285

In [50]:
df['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [51]:
corpus[0]

'house dem aide even see comey letter jason chaffetz tweeted'

# 4.Vectorization (Convert Text data into the Vector)

In [52]:
tf = TfidfVectorizer()
x = tf.fit_transform(corpus).toarray()
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [53]:
y = df['label']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

## Data splitting into the train and test

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 10, stratify = y )

In [55]:
len(x_train),len(y_train)


(12799, 12799)

In [56]:
len(x_test), len(y_test)

(5486, 5486)

## 5. Model Building

In [57]:
# Random Forest Classifier
rf = RandomForestClassifier()


In [58]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [59]:
# Logistic regression Classifier
lg=LogisticRegression()


In [60]:
lg.fit(x_train,y_train)

LogisticRegression()

## 6. Model Evaluation

In [61]:
# Random Forest
y_pred = rf.predict(x_test)
accuracy_score_ = accuracy_score(y_test,y_pred) 
accuracy_score_

0.940211447320452

In [62]:
# Logistic Regression
y_predict=lg.predict(x_test)
accuracy_scr=accuracy_score(y_test,y_predict)
print(accuracy_scr)

0.9228946409041195


In [63]:
## Evaluation function 
class Evaluation:
    
    def __init__(self,model,x_train,x_test,y_train,y_test):
        self.model = model
        self.x_train = x_train
        self.x_test = x_test
        self.y_train = y_train
        self.y_test = y_test
        
    def train_evaluation(self):
        y_pred_train = self.model.predict(self.x_train)
        
        acc_scr_train = accuracy_score(self.y_train,y_pred_train)
        print("Accuracy Score On Training Data Set : ",acc_scr_train)
        print()
        
        con_mat_train = confusion_matrix(self.y_train,y_pred_train)
        print("Confusion Matrix On Training Data Set :\n",con_mat_train)
        print()
        
        class_rep_train = classification_report(self.y_train,y_pred_train)
        print("Classification Report On Training Data Set :\n",class_rep_train)
        
        
    def test_evaluation(self):
        y_pred_test = self.model.predict(self.x_test)
        
        acc_scr_test = accuracy_score(self.y_test,y_pred_test)
        print("Accuracy Score On Testing Data Set :",acc_scr_test)
        print()
        
        con_mat_test = confusion_matrix(self.y_test,y_pred_test)
        print("Confusion Matrix On Testing Data Set :\n",con_mat_test)
        print()
        
        class_rep_test = classification_report(self.y_test,y_pred_test)
        print("Classification Report On Testing Data Set :\n",class_rep_test)
        
        

# Predicting acuuracies for Random Forest Classifier

In [64]:
#Checking the accuracy on training dataset

Evaluation(rf,x_train, x_test, y_train, y_test).train_evaluation()

Accuracy Score On Training Data Set :  1.0

Confusion Matrix On Training Data Set :
 [[7252    0]
 [   0 5547]]

Classification Report On Training Data Set :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      7252
           1       1.00      1.00      1.00      5547

    accuracy                           1.00     12799
   macro avg       1.00      1.00      1.00     12799
weighted avg       1.00      1.00      1.00     12799



In [65]:
#Checking the accuracy on testing dataset
Evaluation(rf,x_train, x_test, y_train, y_test).test_evaluation()

Accuracy Score On Testing Data Set : 0.940211447320452

Confusion Matrix On Testing Data Set :
 [[2839  270]
 [  58 2319]]

Classification Report On Testing Data Set :
               precision    recall  f1-score   support

           0       0.98      0.91      0.95      3109
           1       0.90      0.98      0.93      2377

    accuracy                           0.94      5486
   macro avg       0.94      0.94      0.94      5486
weighted avg       0.94      0.94      0.94      5486



# Predicting accuracies for Logistic Regression 

In [66]:
# Checking the accuracy for training data
Evaluation(lg,x_train,x_test,y_train,y_test).train_evaluation()

Accuracy Score On Training Data Set :  0.943354949605438

Confusion Matrix On Training Data Set :
 [[6608  644]
 [  81 5466]]

Classification Report On Training Data Set :
               precision    recall  f1-score   support

           0       0.99      0.91      0.95      7252
           1       0.89      0.99      0.94      5547

    accuracy                           0.94     12799
   macro avg       0.94      0.95      0.94     12799
weighted avg       0.95      0.94      0.94     12799



In [67]:
# Checking accuracy for testing data
Evaluation(lg,x_train,x_test,y_train,y_test).test_evaluation()

Accuracy Score On Testing Data Set : 0.9228946409041195

Confusion Matrix On Testing Data Set :
 [[2744  365]
 [  58 2319]]

Classification Report On Testing Data Set :
               precision    recall  f1-score   support

           0       0.98      0.88      0.93      3109
           1       0.86      0.98      0.92      2377

    accuracy                           0.92      5486
   macro avg       0.92      0.93      0.92      5486
weighted avg       0.93      0.92      0.92      5486



# Prediction pipeline

In [68]:
class Preprocessing:
    
    def __init__(self,data):
        self.data = data
        
    def text_preprocessing_user(self):
        lm = WordNetLemmatizer()
        pred_data = [self.data]    
        preprocess_data = []
        for data in pred_data:
            review = re.sub('^a-zA-Z0-9',' ', data)
            review = review.lower()
            review = review.split()
            review = [lm.lemmatize(x) for x in review if x not in stopwords]
            review = " ".join(review)
            preprocess_data.append(review)
        return preprocess_data

In [69]:
df['title'][2]


'Why the Truth Might Get You Fired'

In [70]:
data = 'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'
Preprocessing(data).text_preprocessing_user()

['flynn: hillary clinton, big woman campus - breitbart']

# Prediction 

In [71]:
#Function for prediction process
class Prediction:
    
    def __init__(self,pred_data, model):
        self.pred_data = pred_data
        self.model = model
        
    def prediction_model(self):
        preprocess_data = Preprocessing(self.pred_data).text_preprocessing_user()
        data = tf.transform(preprocess_data)
        prediction = self.model.predict(data)
        
        if prediction [0] == 0 :
            return "The News Is Fake"
        
        else:
            return "The News Is Real"

In [72]:
# Random Forest Classifier
data = 'Why the Truth Might Get You Fired'
Prediction(data,rf).prediction_model()


'The News Is Real'

In [73]:
# logistic Regression 
data="why the Thruth Might Get You Fired"
Prediction(data,lg).prediction_model()

'The News Is Real'